@baseUrl = {{$processEnv HOST}}
@port = {{$processEnv PORT}}

### Get all contacts
GET https://{{baseUrl}}/contacts
Content-Type: application/json

### Get single contact
GET https://{{baseUrl}}/contacts/65f897413357d2adfa732f99
Content-Type: application/json

### Create new contact
POST https://{{baseUrl}}/contacts
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "john.doe@example.com",
    "favoriteColor": "blue",
    "birthday": "1990-01-01"
}

### Update contact
PUT https://{{baseUrl}}/contacts/65f897413357d2adfa732f99
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Smith",
    "email": "john.smith@example.com",
    "favoriteColor": "red",
    "birthday": "1990-01-01"
}

### Delete contact
DELETE https://{{baseUrl}}/contacts/65f897413357d2adfa732f99
Content-Type: application/json